### PR TITLE
Adding verbiage for slack and how to edit docs. 

### PR DESCRIPTION
**Pull request by joshmccall221**
Quick and dirty! 

Feel free to tell critique.

### CODE REVIEW

**Comment by toranb** [comment]
Thanks @joshmccall221 !!!

I love the community section but I'd prefer to drop the jekyll docs mention from the README if that's cool. I see that as "how to stand up/build/run the docs website" myself and prefer to keep that as clean/n' simple as possible :)

**Comment by toranb** [comment]
ping ;) hey @joshmccall221 did you want to drop the jekyll stuff so we can merge in this epic PR ?

Much appreciated dude!

**Comment by joshmccall221** [comment]
But how do we encourage peeps to update docs???

Yeah, I'll drop the jekyll stuff... give me a sec

**Comment by joshmccall221** [comment]
There we go!

**Pull request merged**
