### PR TITLE
Remove jQuery

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
This is an automated PR from: https://github.com/NullVoxPopuli/ember-jSquirrels

     In an effort to better ready the Ember ecosystem for the modern web, jQuery must be removed.

     There have been native replacements for jQuery APIs for quite a few years.

     Removing jQuery will reduce everyone's app vendor size by 30-80kb after min+gzip, depending on the jQuery version.

### CODE REVIEW

**Comment by toranb** [comment]
jQuery is only used in test code for ember redux ($.ajax) and none of the changes here are related so what is the migration plan to drop jQuery for this situation and how costly is it assuming test assets won’t ship to production?

**Comment by NullVoxPopuli** [comment]
> ajax

Hmm, I guess the codemods didn't catch it, or don't know how to deal with ajax yet.

> migration plan

fetch is the native alternative for requests and such

> How costly?

Converting to fetch is usually pretty straightforward

**Comment by toranb** [comment]
@NullVoxPopuli if you can get this file migrated from ajax to fetch I will certainly thank you ;)

https://github.com/ember-redux/ember-redux/blob/master/tests/helpers/ajax.js

**Comment by NullVoxPopuli** [comment]
I did some things to help get migrated -- but it looks like I'm mostly running in to some ember-integration related issues now :(

**Comment by toranb** [comment]
@NullVoxPopuli can we close out this PR at some point? This addon doesn't use jQuery for anything but the test build and I'm fine with that for the moment. No hard feelings here btw - just looking to cleanup stale pull requests that aren't moving forward

**Pull request closed without merging**
