### PR TITLE
Move state calls up, add init for es-2015 class

### PR DESCRIPTION
**Pull request by BobrImperator**
@toranb Please take a look

Related to #180, as the issue still occurs.

### CODE REVIEW

**Comment by BobrImperator** [comment]
Moving the calls for other life cycle hooks should be also considered, because if anyone were to access the state in DidReceiveAttrs for example, they'd end up with older state, if it happened to be updated.

**Comment by toranb** [comment]
Just a heads up :) the es2015 init addition here is something I truly don’t want in the codebase (as es2019 solves that and was added for only that compat reason).

The root cause here is “why” doesn’t the conditional for EmberObject catch and connect up as it does wirh test/dev. Until we understand that more deeply I won’t be merging a bandaid over this to solve the immediate defect you ran into.

**Comment by BobrImperator** [comment]
Sure, but I dunno If I'll be able to debunk the issue if  I know just as much.
The only things I know at the moment is that it hits the `es-2015` connector which has no init, and basically makes no call to the state at all.
Also apparently this occurs for Chrome and not for Firefox, and so it gets as much more interesting and the try/catch when calling the component returns
`Cannot read property 'proto' of undefined` instead of `Class constructor cannot be invoked without 'new'`

**Comment by BobrImperator** [comment]
Also please take a look at the changes again, I couldn't help but think that `es-2015` file is redundant.

**Comment by BobrImperator** [comment]
Alright! I DE-BUNKED it.
I've had a revelation, I simply ran tests in production environment on master branch in addon, and 1 of them failed, the one You've added for this issue. Then I ran tests on this PR branch, and it worked :)
I've modified ember-try to run in environment production right now.

**Comment by toranb** [comment]
@BobrImperator  thanks for the extra effort on this today! I'm glad to see the nasty hacks I added last week gone and this works for ember 2.18+ so it should be g2g for everyone (for all envs dev/test/prod).

**Comment by toranb** [comment]
@BobrImperator  I've published this on npm as v4.0.3

**Comment by BobrImperator** [comment]
Lovely! Thank you very much!
<3

**Pull request merged**
